import yfinance as yf
from ta.momentum import *
from ta.volume import *
from ta.volatility import *
from ta.trend import *
from ta.others import *

ticker = yf.Ticker('BTC-USD')
df = ticker.history(period="max")[['Open', 'High', 'Low', 'Close', 'Volume']]
df['awesome_oscillator'] = awesome_oscillator(df['High'], df['Low'])
df['kama'] = kama(df['Close'])
df['ppo'] = ppo(df['Close'])
df['ppo_signal'] = ppo_signal(df['Close'])
df['pvo'] = pvo(df['Volume'])
df['pvo_signal'] = pvo_signal(df['Volume'])
df['roc'] = roc(df['Close'])
df['rsi'] = rsi(df['Close'])
df['stochrsi'] = stochrsi(df['Close'])
df['stoch'] = stoch(df['Close'], df['High'], df['Low'])
df['stoch_signal'] = stoch_signal(df['Close'], df['High'], df['Low'])
df['tsi'] = tsi(df['Close'])
df['ultimate_oscillator'] = ultimate_oscillator(df['High'], df['Low'], df['Close'])
df['williams_r'] = williams_r(df['High'], df['Low'], df['Close'])
df['acc_dist_index'] = acc_dist_index(df['High'], df['Low'], df['Close'], df['Volume'])
df['chaikin_money_flow'] = chaikin_money_flow(df['High'], df['Low'], df['Close'], df['Volume'])
df['ease_of_movement'] = ease_of_movement(df['High'], df['Low'], df['Volume'])
df['sma_ease_of_movement'] = sma_ease_of_movement(df['High'], df['Low'], df['Volume'])
df['force_index'] = force_index(df['Close'], df['Volume'])
df['money_flow_index'] = money_flow_index(df['High'], df['Low'], df['Close'], df['Volume'])
df['negative_volume_index'] = negative_volume_index(df['Close'], df['Volume'])
df['on_balance_volume'] = on_balance_volume(df['Close'], df['Volume'])
df['volume_price_trend'] = volume_price_trend(df['Close'], df['Volume'])
df['volume_weighted_average_price'] = volume_weighted_average_price(df['High'], df['Low'], df['Close'], df['Volume'])
df['average_true_range'] = average_true_range(df['High'], df['Low'], df['Close'])
df['bollinger_hband'] = bollinger_hband(df['Close'])
df['bollinger_lband'] = bollinger_lband(df['Close'])
df['bollinger_mavg'] = bollinger_mavg(df['Close'])
df['bollinger_pband'] = bollinger_pband(df['Close'])
df['bollinger_wband'] = bollinger_wband(df['Close'])
df['donchian_channel_hband'] = donchian_channel_hband(df['High'], df['Low'], df['Close'])
df['donchian_channel_lband'] = donchian_channel_lband(df['High'], df['Low'], df['Close'])
df['donchian_channel_mband'] = donchian_channel_mband(df['High'], df['Low'], df['Close'])
df['donchian_channel_pband'] = donchian_channel_pband(df['High'], df['Low'], df['Close'])
df['donchian_channel_wband'] = donchian_channel_wband(df['High'], df['Low'], df['Close'])
df['keltner_channel_hband'] = keltner_channel_hband(df['High'], df['Low'], df['Close'])
df['keltner_channel_lband'] = keltner_channel_lband(df['High'], df['Low'], df['Close'])
df['keltner_channel_mband'] = keltner_channel_mband(df['High'], df['Low'], df['Close'])
df['keltner_channel_pband'] = keltner_channel_pband(df['High'], df['Low'], df['Close'])
df['keltner_channel_wband'] = keltner_channel_wband(df['High'], df['Low'], df['Close'])
df['ulcer_index'] = ulcer_index(df['Close'])
df['aroon_down'] = aroon_down(df['Close'])
df['aroon_up'] = aroon_up(df['Close'])
df['cci'] = cci(df['High'], df['Low'], df['Close'])
df['dpo'] = dpo(df['Close'])
df['ema_indicator'] = ema_indicator(df['Close'])
df['ichimoku_a'] = ichimoku_a(df['High'], df['Low'])
df['ichimoku_b'] = ichimoku_b(df['High'], df['Low'])
df['ichimoku_base_line'] = ichimoku_base_line(df['High'], df['Low'])
df['ichimoku_conversion_line'] = ichimoku_conversion_line(df['High'], df['Low'])
df['kst'] = kst(df['Close'])
df['kst_sig'] = kst_sig(df['Close'])
df['macd'] = macd(df['Close'])
df['macd_signal'] = macd_signal(df['Close'])
df['mass_index'] = mass_index(df['High'], df['Low'])
df['sma'] = sma_indicator(df['Close'])
df['stc'] = stc(df['Close'])
df['trix'] = trix(df['Close'])
df['vortex_indicator_neg'] = vortex_indicator_neg(df['High'], df['Low'], df['Close'])
df['vortex_indicator_pos'] = vortex_indicator_pos(df['High'], df['Low'], df['Close'])
df['cumulative_return'] = cumulative_return(df['Close'])
df['daily_return'] = daily_return(df['Close'])

df.to_csv('ta.csv')
